"""CalculiX (ccx) driver: build .inp decks, run the solver, parse results.

Units: mm, N, MPa throughout (consistent unit system; density would be
tonne/mm^3 in dynamic runs - static only here).

Deck model
----------
A Deck is nodes + element blocks + named sets + materials/sections +
optional surfaces, rigid bodies and contact pairs + one or more Steps.
Node/element numbering: meshio 0-based indices become 1-based ids; element
ids run sequentially over the blocks in order. Extra (non-mesh) nodes such
as rigid-body reference nodes get ids above the mesh range.

Parsers
-------
parse_frd: nodal DISP/STRESS blocks per increment (fixed-width format).
parse_dat: `*NODE PRINT` outputs, e.g. reaction-force totals per increment.
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
from dataclasses import dataclass, field

import numpy as np


# ---------------------------------------------------------------------------
# deck definition
# ---------------------------------------------------------------------------
@dataclass
class ElementBlock:
    name: str            # ELSET name
    ccx_type: str        # e.g. C3D10, CPS6
    cells: np.ndarray    # (n_elem, n_nodes_per_elem), 0-based node indices


@dataclass
class MaterialDef:
    name: str
    E: float
    nu: float
    plastic: list[tuple[float, float]] | None = None  # (stress MPa, plastic strain)


@dataclass
class Section:
    elset: str
    material: str
    thickness: float | None = None   # plane-stress thickness, None for 3D


@dataclass
class Step:
    name: str = "step"
    nlgeom: bool = False
    static_line: str | None = None   # "0.02, 1.0, 1e-6, 0.05" or None for default
    max_increments: int = 1000
    # (target nset-or-node-id, first dof, last dof, value)
    boundaries: list[tuple] = field(default_factory=list)
    # (target nset-or-node-id, dof, value)
    cloads: list[tuple] = field(default_factory=list)
    # (nset, keys e.g. "RF", totals_only)
    node_prints: list[tuple] = field(default_factory=list)
    node_file: str = "U"             # frd nodal output request
    el_file: str = "S"               # frd element output request


@dataclass
class Deck:
    points: np.ndarray                      # (n, 3) mesh nodes
    blocks: list[ElementBlock]
    nsets: dict[str, np.ndarray] = field(default_factory=dict)      # 0-based
    raw_nsets: dict[str, list[int]] = field(default_factory=dict)   # 1-based literal ids
    extra_nodes: dict[int, tuple] = field(default_factory=dict)     # id -> xyz
    materials: list[MaterialDef] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)
    # surface name -> list of (element id 1-based, face id 1..4)
    surfaces: dict[str, list[tuple[int, int]]] = field(default_factory=dict)
    # (nset name, ref node id, rot node id)
    rigid_bodies: list[tuple[str, int, int]] = field(default_factory=list)
    # (interaction name, linear pressure-overclosure stiffness MPa/mm)
    interactions: list[tuple[str, float]] = field(default_factory=list)
    # (interaction name, slave surface, master surface)
    contact_pairs: list[tuple[str, str, str]] = field(default_factory=list)
    # global amplitude-independent boundaries applied before all steps
    base_boundaries: list[tuple] = field(default_factory=list)
    steps: list[Step] = field(default_factory=list)

    def first_free_node_id(self) -> int:
        return len(self.points) + len(self.extra_nodes) + 1


def _fmt_ids(ids, per_line=12):
    ids = list(ids)
    lines = []
    for i in range(0, len(ids), per_line):
        lines.append(", ".join(str(x) for x in ids[i:i + per_line]) + ",")
    return "\n".join(lines)


def write_inp(deck: Deck, path: str) -> str:
    out = []
    ap = out.append
    ap("** generated by node_kit.fea - units mm, N, MPa")
    ap("*NODE")
    for i, (x, y, z) in enumerate(deck.points, start=1):
        ap(f"{i}, {x:.9g}, {y:.9g}, {z:.9g}")
    for nid, (x, y, z) in sorted(deck.extra_nodes.items()):
        ap(f"{nid}, {x:.9g}, {y:.9g}, {z:.9g}")

    eid = 1
    for blk in deck.blocks:
        ap(f"*ELEMENT, TYPE={blk.ccx_type}, ELSET={blk.name}")
        for conn in blk.cells:
            ids = [str(int(n) + 1) for n in conn]
            ap(f"{eid}, " + ", ".join(ids))
            eid += 1

    for name, idx in deck.nsets.items():
        ap(f"*NSET, NSET={name}")
        ap(_fmt_ids([int(i) + 1 for i in np.asarray(idx).ravel()]))

    for name, ids in deck.raw_nsets.items():
        ap(f"*NSET, NSET={name}")
        ap(_fmt_ids(ids))

    for name, faces in deck.surfaces.items():
        ap(f"*SURFACE, NAME={name}, TYPE=ELEMENT")
        for (elem_id, face_id) in faces:
            ap(f"{elem_id}, S{face_id}")

    for mat in deck.materials:
        ap(f"*MATERIAL, NAME={mat.name}")
        ap("*ELASTIC")
        ap(f"{mat.E:.6g}, {mat.nu}")
        if mat.plastic:
            ap("*PLASTIC")
            for (sig, eps) in mat.plastic:
                ap(f"{sig:.6g}, {eps:.6g}")

    for sec in deck.sections:
        ap(f"*SOLID SECTION, ELSET={sec.elset}, MATERIAL={sec.material}")
        if sec.thickness is not None:
            ap(f"{sec.thickness}")

    for (nset, ref, rot) in deck.rigid_bodies:
        ap(f"*RIGID BODY, NSET={nset}, REF NODE={ref}, ROT NODE={rot}")

    for (name, k) in deck.interactions:
        ap(f"*SURFACE INTERACTION, NAME={name}")
        ap("*SURFACE BEHAVIOR, PRESSURE-OVERCLOSURE=LINEAR")
        ap(f"{k:.6g}")

    for (inter, slave, master) in deck.contact_pairs:
        ap(f"*CONTACT PAIR, INTERACTION={inter}, TYPE=SURFACE TO SURFACE")
        ap(f"{slave}, {master}")

    if deck.base_boundaries:
        ap("*BOUNDARY")
        for (target, d1, d2, val) in deck.base_boundaries:
            ap(f"{target}, {d1}, {d2}, {val}")

    for st in deck.steps:
        nl = ", NLGEOM" if st.nlgeom else ""
        ap(f"*STEP{nl}, INC={st.max_increments}")
        ap("*STATIC")
        if st.static_line:
            ap(st.static_line)
        if st.boundaries:
            ap("*BOUNDARY")
            for (target, d1, d2, val) in st.boundaries:
                ap(f"{target}, {d1}, {d2}, {val}")
        if st.cloads:
            ap("*CLOAD")
            for (target, dof, val) in st.cloads:
                ap(f"{target}, {dof}, {val:.9g}")
        for (nset, keys, totals) in st.node_prints:
            tot = ", TOTALS=ONLY" if totals else ""
            ap(f"*NODE PRINT, NSET={nset}{tot}")
            ap(keys)
        if st.node_file:
            ap("*NODE FILE")
            ap(st.node_file)
        if st.el_file:
            ap("*EL FILE")
            ap(st.el_file)
        ap("*END STEP")

    pathlib.Path(path).write_text("\n".join(out) + "\n")
    return path


# ---------------------------------------------------------------------------
# solver
# ---------------------------------------------------------------------------
class CcxError(RuntimeError):
    pass


def run_ccx(workdir: str, jobname: str, timeout_s: int = 3600) -> dict:
    """Run ccx on workdir/jobname.inp; return paths to result files."""
    env = dict(os.environ)
    env.setdefault("OMP_NUM_THREADS", str(os.cpu_count() or 1))
    proc = subprocess.run(
        ["ccx", "-i", jobname],
        cwd=workdir, env=env, capture_output=True, text=True,
        timeout=timeout_s,
    )
    frd = pathlib.Path(workdir) / f"{jobname}.frd"
    log = proc.stdout + proc.stderr
    if "*ERROR" in log and not frd.exists():
        raise CcxError(f"ccx failed:\n{log[-4000:]}")
    if not frd.exists():
        raise CcxError(
            f"ccx produced no .frd (rc={proc.returncode}):\n{log[-4000:]}"
        )
    return {
        "frd": str(frd),
        "dat": str(pathlib.Path(workdir) / f"{jobname}.dat"),
        "log": log,
        "returncode": proc.returncode,
    }


# ---------------------------------------------------------------------------
# result parsing
# ---------------------------------------------------------------------------
def parse_frd(path: str) -> dict[str, list[dict[int, np.ndarray]]]:
    """Parse nodal result blocks from a .frd file.

    Returns {result_name: [increment0, increment1, ...]} where each increment
    is {node_id: np.array(values)}. Handles the fixed-width format:
    ' -1' + I10 node id + 6 x E12.5 values (continuation lines ' -2').
    """
    results: dict[str, list[dict[int, np.ndarray]]] = {}
    current_name = None
    current: dict[int, list[float]] | None = None
    last_node = None

    def flush():
        nonlocal current, current_name
        if current_name is not None and current is not None:
            results.setdefault(current_name, []).append(
                {nid: np.asarray(vals) for nid, vals in current.items()}
            )
        current, current_name = None, None

    with open(path, "r", errors="replace") as fh:
        for line in fh:
            if line.startswith(" -4"):
                flush()
                current_name = line[5:13].strip()
                current = {}
            elif line.startswith(" -3"):
                flush()
            elif current is not None and line.startswith(" -1"):
                nid = int(line[3:13])
                vals = _read_floats(line[13:])
                current[nid] = vals
                last_node = nid
            elif current is not None and line.startswith(" -2") and last_node:
                current[last_node].extend(_read_floats(line[13:]))
    flush()
    return results


def _read_floats(chunk: str) -> list[float]:
    vals = []
    chunk = chunk.rstrip("\n")
    for i in range(0, len(chunk) - 11, 12):
        piece = chunk[i:i + 12].strip()
        if piece:
            vals.append(float(piece))
    return vals


_DAT_HEADER = re.compile(r"^\s*(.+?)\s+for set (\S+) and time\s+([0-9.eE+-]+)")


def parse_dat(path: str) -> list[dict]:
    """Parse *NODE PRINT outputs from a .dat file.

    Returns a list of {'label', 'set', 'time', 'rows': np.ndarray} in file
    order; 'rows' has one row per printed line (node id first if present).
    """
    entries: list[dict] = []
    lines = pathlib.Path(path).read_text(errors="replace").splitlines()
    i = 0
    while i < len(lines):
        m = _DAT_HEADER.match(lines[i])
        if not m:
            i += 1
            continue
        label, setname, time = m.group(1).strip(), m.group(2), float(m.group(3))
        i += 1
        rows = []
        while i < len(lines):
            s = lines[i].strip()
            if not s:
                if rows:
                    break
                i += 1
                continue
            if _DAT_HEADER.match(lines[i]):
                break
            try:
                rows.append([float(tok) for tok in s.split()])
            except ValueError:
                break
            i += 1
        entries.append({
            "label": label, "set": setname, "time": time,
            "rows": np.asarray(rows) if rows else np.empty((0,)),
        })
    return entries


def dat_series(entries: list[dict], label_contains: str,
               setname: str) -> list[tuple[float, np.ndarray]]:
    """(time, first-row values) history for one printed quantity and set."""
    out = []
    for e in entries:
        if label_contains in e["label"] and e["set"] == setname.upper():
            if e["rows"].size:
                out.append((e["time"], e["rows"][0]))
    return out
